### ISSUE TITLE
Lỗi ValueError: malformed string

### ISSUE THREAD

**Issue by voccer** [deepai-solutions/core_nlp#1]
Em chạy thì nó bị lỗi này mà ko biết sửa thế nào cả

Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    model_path='models/pretrained_tokenizer.crfsuite')
  File "/home/voccer/Desktop/text_classification/core_nlp/tokenization/crf_tokenizer.py", line 98, in __init__
    self.bi_grams = load_n_grams(config_root_path + bi_grams_path)
  File "/home/voccer/Desktop/text_classification/core_nlp/tokenization/utils.py", line 10, in load_n_grams
    words = ast.literal_eval(words)
  File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python2.7/ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string
voccer@voccer:~/Desktop/text_classification/core_nlp$ python demo.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    model_path='models/pretrained_tokenizer.crfsuite')
  File "/home/voccer/Desktop/text_classification/core_nlp/tokenization/crf_tokenizer.py", line 98, in __init__
    self.bi_grams = load_n_grams(config_root_path + bi_grams_path)
  File "/home/voccer/Desktop/text_classification/core_nlp/tokenization/utils.py", line 10, in load_n_grams
    words = ast.literal_eval(words)
  File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python2.7/ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string

**Comment by pencilforever** [comment]
Bạn dùng python 3.x nhé, mình mới test trên python 3.6.
Bạn có thể xem thêm file requirements.txt nha.
